#logging:
#  config: classpath:logback.xml
server:
  servlet:
    ## 统一编码处理
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  ## tomcat编码处理
  tomcat:
    uri-encoding: utf-8
  ## 错误信息处理
  error:
    include-binding-errors=never
    include-stacktrace=never
    include-exception=false

spring:
  application:
    name: mini-mvc
  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true





