#logging:
#  config: classpath:logback.xml
server:
  servlet:
    encoding:
      enabled: false
      charset: UTF-8
      force: true
spring:
  application:
    name: mini-mvc
  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true




