## 配置开发环境配置
server:
  port: 8080
  servlet:
    context-path: /mini
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mini_test?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    jndi-name: jdbc/mini
    password: Qwe123456!
    username: root




